"departementserien":
        "collection": "riksdagen"
        "collection_qid": ""
        "workdirectory": "data/se/riksdagen/departementserien"
        "qid": "Q123501464"
"proposition":
        "collection": "riksdagen"
        "collection_qid": ""
        "workdirectory": "data/se/riksdagen/proposition"
        "qid": "Q123501430"
